"""empty message

Revision ID: 68b65e1a0400
Revises: 
Create Date: 2018-05-31 16:13:00.491633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68b65e1a0400'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instagram_img_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_user_id', sa.String(length=30), nullable=True),
    sa.Column('img_user_name', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('user_profile_url', sa.String(length=150), nullable=True),
    sa.Column('image_counts', sa.Integer(), nullable=True),
    sa.Column('crawled_time', sa.String(length=20), nullable=True),
    sa.Column('is_crawled', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('img_user_id')
    )
    op.create_table('user',
    sa.Column('userid', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=10), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('userid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('instagram_img_user')
    # ### end Alembic commands ###
