"""empty message

Revision ID: d9bfed7dbf01
Revises: 68b65e1a0400
Create Date: 2018-06-04 17:13:20.617591

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd9bfed7dbf01'
down_revision = '68b65e1a0400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.String(length=128), nullable=False))
    op.drop_column('user', 'userid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('userid', mysql.VARCHAR(length=128), nullable=False))
    op.drop_column('user', 'id')
    # ### end Alembic commands ###
